# Generated by Django 5.2.6 on 2025-09-28 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_value', models.IntegerField()),
                ('date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_project.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_project.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('schedule_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_project.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_project.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_project.teacher')),
            ],
        ),
    ]
