# Generated by Django 5.2.6 on 2025-09-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_project', '0002_grade_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.CharField(max_length=100),
        ),
    ]
